name: Treinamento e Deploy do Modelo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar treinamento do modelo
      run: python train_model.py

    - name: Salvar modelo como artefato
      uses: actions/upload-artifact@v3
      with:
        name: modelo-regressao
        path: linear_model.pkl
